### ISSUE TITLE
Trying to build without a board selected

### ISSUE THREAD

**Issue by joaoantoniocardoso** [mupuf/arduide#4]
This is a minor issue and as soon as I read the output of utility dock I understood what happen.

When I first opened Arduide I was able to immediatly press 'build'. Because I didn't selected a board it causes an error that aborts the build process. The "Board" menu has a blank item that is related to that and it would happen if you simply choose that blank item in the "Board" menu.

> avr-g++: error: missing device or architecture after '-mmcu='

**Comment by mupuf** [comment]
Thanks for reporting it! We will have a look at it :)

**Comment by patrickelectric** [comment]
After 3/26 I'll look for bugs and test some boards like, arduino nano, uno and mini. With this I will check the upload process with FTDI programmer and Arduino as ISP :muscle:
